## Практическое задание №4.

## Системы линейных уравнений. Часть 1

### Задача 1

_**Условие:**_

Решите систему уравнений методом Гаусса:


$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4
\end{cases}$$

_**Решение:**_

Расширенная матрица данной системы уравнений:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
2 & 1 & -1 & 1\\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$$

Вычтем из второй строки первую, умноженную на 2, а из третьей - вычтем первую:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
0 & -1 & 1 & 5\\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$$

Получившаяся матрица соответствует системе:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
-x_{2} + x_{3} + 5x_{4}=-2, \\
-2x_{3} + 3x_{4}=4
\end{cases}$$

Рассматрим в качестве свободного параметра $x_{4}=c$ и, выражая остальные переменные через $c$, получим:

$$x_{4}=c,$$
$$-2x_{3} + 3c = 4 \; \Leftrightarrow \; x_{3} = (3c - 4)/2,$$
$$-x_{2} + (3c - 4)/2 + 5c = -2 \; \Leftrightarrow \; x_{2} = 13с/2$$
$$x_{1} + 13с/2 - (3c - 4)/2 - 2c = 0 \; \Leftrightarrow \; x_{1} = -3с - 2$$

Таким образом, общее решение данной системы:

$$x_{4}=c,$$
$$x_{3} = (3c - 4)/2,$$
$$x_{2} = 13с/2$$
$$x_{1} = -3с - 2$$

### Задача 2

_**Условие:**_

Проверьте на совместность и выясните, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

_**Решение:**_

_**a)**_

$\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$

Для данной системы уравнений расширенная матрица $\tilde A$:

$$\begin{pmatrix}
\left.\begin{matrix}
3 & -1 & 1\\ 
2 & -5 & -3\\ 
1 & 1 & -1
\end{matrix}\right|
\begin{matrix}
4\\ 
-17\\
0
\end{matrix}
\end{pmatrix}$$

In [1]:
import numpy as np

A = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
A_tilda = np.array([[3, -1, 1, 4], [2, -5, -3, -17], [1, 1, -1, 0]])
print(f'Матрица A:\n{A}')
print(f'Матрица A_tilda:\n{A_tilda}')
print(f'Ранг A:\n{np.linalg.matrix_rank(A)}')
print(f'Ранг A_tilda:\n{np.linalg.matrix_rank(A_tilda)}')

Матрица A:
[[ 3 -1  1]
 [ 2 -5 -3]
 [ 1  1 -1]]
Матрица A_tilda:
[[  3  -1   1   4]
 [  2  -5  -3 -17]
 [  1   1  -1   0]]
Ранг A:
3
Ранг A_tilda:
3


Число неизвестных $n = 3$, таким образом, $rankA = rank \tilde A = n = 3$, из чего следует, что данная система уравнений - совместная и определенная, то есть имеет единственное решение.

_**б)**_

$\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$

Для данной системы уравнений расширенная матрица $\tilde B$:

$$\begin{pmatrix}
\left.\begin{matrix}
2 & -4 & 6\\ 
1 & -2 & 3\\ 
3 & -6 & 9
\end{matrix}\right|
\begin{matrix}
1\\ 
-2\\
5
\end{matrix}
\end{pmatrix}$$

In [2]:
B = np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9]])
B_tilda = np.array([[2, -4, 6, 1], [1, -2, 3, -2], [3, -6, 9, 5]])
print(f'Матрица B:\n{B}')
print(f'Матрица B_tilda:\n{B_tilda}')
print(f'Ранг B:\n{np.linalg.matrix_rank(B)}')
print(f'Ранг B_tilda:\n{np.linalg.matrix_rank(B_tilda)}')

Матрица B:
[[ 2 -4  6]
 [ 1 -2  3]
 [ 3 -6  9]]
Матрица B_tilda:
[[ 2 -4  6  1]
 [ 1 -2  3 -2]
 [ 3 -6  9  5]]
Ранг B:
1
Ранг B_tilda:
2


Получаем, что $rankB = 1 < rank \tilde B  = 2$, поэтому данная система уравнений - несовместная, то есть не имеет решений.

_**в)**_

$\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

Для данной системы уравнений расширенная матрица $\tilde C$:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 5\\ 
3 & 1 & -8
\end{matrix}\right|
\begin{matrix}
4\\ 
-2
\end{matrix}
\end{pmatrix}$$

In [3]:
C = np.array([[1, 2, 5], [3, 1, -8]])
C_tilda = np.array([[1, 2, 5, 4], [3, 1, -8, -2]])
print(f'Матрица C:\n{C}')
print(f'Матрица C_tilda:\n{C_tilda}')
print(f'Ранг C:\n{np.linalg.matrix_rank(C)}')
print(f'Ранг C_tilda:\n{np.linalg.matrix_rank(C_tilda)}')

Матрица C:
[[ 1  2  5]
 [ 3  1 -8]]
Матрица C_tilda:
[[ 1  2  5  4]
 [ 3  1 -8 -2]]
Ранг C:
2
Ранг C_tilda:
2


Число неизвестных $n = 3$, таким образом, $rankA = rank \tilde A = 2 < n = 3$, из чего следует, что данная система уравнений - совместная и неопределенная и имеет бесконечное количество решений.

### Задача 3

_**Условие:**_

Проверьте на совместность и выясните, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей:

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

_**Решение:**_

Очевидно, что линейной зависимости векторов нет, поэтому $rankA = rank \tilde A = 4$. Число неизвестных $n = 4$, таким образом, $rankA = rank \tilde A = n = 4$, из чего следует, что данная система уравнений - совместная и определенная, то есть имеет единственное решение.

### Задача 4

_**Условие:**_

Дана система линейных уравнений, заданная расширенной матрицей:

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}$$

Найдите соотношение между параметрами $a$, $b$ и $c$, при которых система считается несовместной.

_**Решение:**_

Вычтем из второй строки первую умноженную на 2, а из третьей вычтем первую умноженную на 3:

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
2 & 1 & 0\\ 
4 & 2 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b-2a\\
c-3a
\end{matrix}
\end{pmatrix}$$

Вычтем из третьей строки вторую умноженную на 2:

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
2 & 1 & 0\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b-2a\\
(c-3a)-2(b-2a) \; \Leftrightarrow \; c-2b+a
\end{matrix}
\end{pmatrix}$$

Если $с - 2b + a \neq 0$, то система не имеет решений и является несовместной. В противном случае одну из неизвестных можно выразить через свободный параметр и, следовательно, система имеет бесконечное множество решений.

## Системы линейных уравнений. Часть 2

### Задача 1

_**Условие:**_

Решите систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

_**Решение:**_

_**a)**_

$\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$

Для данной системы уравнений расширенная матрица $\tilde A$:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & -2\\ 
3 & -4
\end{matrix}\right|
\begin{matrix}
1\\ 
7
\end{matrix}
\end{pmatrix}$$

Найдём определитель матрицы коэффициентов $A$:

In [4]:
A = np.array([[1, -2], [3, -4]])

print(f'Матрица A:\n{A}')
print(f'det A:\n{np.linalg.det(A):.1f}')

Матрица A:
[[ 1 -2]
 [ 3 -4]]
det A:
2.0


$DetA \neq 0$ следовательно, система совместна. Найдём определители $detA_{1}$, $detA_{2}$:

In [5]:
A_1 = np.array([[1, -2], [7, -4]])

print(f'Матрица A_1:\n{A_1}')
print(f'det A_1:\n{np.linalg.det(A_1):.1f}')

Матрица A_1:
[[ 1 -2]
 [ 7 -4]]
det A_1:
10.0


In [6]:
A_2 = np.array([[1, 1], [3, 7]])

print(f'Матрица A_2:\n{A_2}')
print(f'det A_2:\n{np.linalg.det(A_2):.1f}')

Матрица A_2:
[[1 1]
 [3 7]]
det A_2:
4.0


Находим решение по формулам Крамера:

$$x_{1} = \frac{detA_{1}}{detA} = \frac{10}{2}=5$$

$$x_{2} = \frac{detA_{2}}{detA} = \frac{4}{2}=2$$

_**б)**_

$\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

Для данной системы уравнений расширенная матрица $\tilde B$:

$$\begin{pmatrix}
\left.\begin{matrix}
2 & -1 & 5\\ 
1 & 1 & -3\\
2 & 4 & 1
\end{matrix}\right|
\begin{matrix}
10\\ 
-2\\
1
\end{matrix}
\end{pmatrix}$$

Найдём определитель матрицы коэффициентов $B$:

In [7]:
B = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])

print(f'Матрица B:\n{B}')
print(f'det B:\n{np.linalg.det(B):.1f}')

Матрица B:
[[ 2 -1  5]
 [ 1  1 -3]
 [ 2  4  1]]
det B:
43.0


$DetB \neq 0$ следовательно, система совместна. Найдём определители $detB_{1}$, $detB_{2}$, $detB_{3}$:

In [8]:
B_1 = np.array([[10, -1, 5], [-2, 1, -3], [1, 4, 1]])

print(f'Матрица B_1:\n{B_1}')
print(f'det B_1:\n{np.linalg.det(B_1):.1f}')

Матрица B_1:
[[10 -1  5]
 [-2  1 -3]
 [ 1  4  1]]
det B_1:
86.0


In [9]:
B_2 = np.array([[2, 10, 5], [1, -2, -3], [2, 1, 1]])

print(f'Матрица B_2:\n{B_2}')
print(f'det B_2:\n{np.linalg.det(B_2):.1f}')

Матрица B_2:
[[ 2 10  5]
 [ 1 -2 -3]
 [ 2  1  1]]
det B_2:
-43.0


In [10]:
B_3 = np.array([[2, -1, 10], [1, 1, -2], [2, 4, 1]])

print(f'Матрица B_3:\n{B_3}')
print(f'det B_3:\n{np.linalg.det(B_3):.1f}')

Матрица B_3:
[[ 2 -1 10]
 [ 1  1 -2]
 [ 2  4  1]]
det B_3:
43.0


$$x_{1} = \frac{detB_{1}}{detB} = \frac{86}{43}=2$$

$$x_{2} = \frac{detB_{2}}{detB} = \frac{-43}{43}=-1$$

$$x_{3} = \frac{detB_{3}}{detB} = \frac{43}{43}=1$$

### Задача 2

_**Условие:**_

Найдите $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

_**Решение:**_

_**a)**_

Исходная матрица $A$:
$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$

Матрица $L_{a}$:
$\begin{pmatrix}
1 & 0 & 0 \\ 
l_{21} & 1 & 0 \\ 
l_{31} & l_{32} & 1
\end{pmatrix}$

- $l_{21}$ определяется путем умножения 1-ой строки на 2
- $l_{31}$ определяется путем умножения 1-ой строки на 3

Таким образом $l_{21} = 2$, $l_{31} = 3$, а получившаяся матрица $U_{a}$ после преобразований будет иметь вид:

$$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 20 & 18
\end{pmatrix}$$

$l_{32}$ определяется путем умножения 2-ой строки на 4.

Таким образом $l_{32} = 4$ и:

$L_{a} =$ 
$\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}$

$U_{a} =$
$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix}$

Проверим с помощью `numpy`:

In [11]:
L_a = np.array([[1, 0, 0], [2, 1, 0], [3, 4, 1]])
U_a = np.array([[1, 2, 4], [0, 5, 4], [0, 0, 2]])

print(f'Матрица L_a\n{L_a}\n')
print(f'Матрица U_a\n{U_a}\n')
print(f'Матрица A = L_a * U_a\n{np.dot(L_a, U_a)}')

Матрица L_a
[[1 0 0]
 [2 1 0]
 [3 4 1]]

Матрица U_a
[[1 2 4]
 [0 5 4]
 [0 0 2]]

Матрица A = L_a * U_a
[[ 1  2  4]
 [ 2  9 12]
 [ 3 26 30]]


_**б)**_

Исходная матрица $B$:
$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$

Матрица $L_{b}$:
$\begin{pmatrix}
1 & 0 & 0 & 0\\ 
l_{21} & 1 & 0 & 0\\ 
l_{31} & l_{32} & 1 & 0\\
l_{41} & l_{42} & l_{43} & 1
\end{pmatrix}$

- $l_{21}$ определяется путем умножения 1-ой строки на 2
- $l_{31}$ определяется путем умножения 1-ой строки на 3
- $l_{41}$ определяется путем умножения 1-ой строки на 4

Таким образом $l_{21} = 2$, $l_{31} = 3$, $l_{41} = 4$, а получившаяся матрица $U_{b}$ после преобразований будет иметь вид:

$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 15 & 23 & 6\\
0 & 18 & 45 & 17
\end{pmatrix}$$

- $l_{32}$ определяется путем умножения 2-ой строки на 5
- $l_{42}$ определяется путем умножения 2-ой строки на 6

Таким образом $l_{32} = 5$, $l_{42} = 6$, а получившаяся матрица $U_{b}$ после преобразований будет иметь вид:

$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 21 & 11
\end{pmatrix}$$

$l_{43}$ определяется путем умножения 3-ей строки на 7

Таким образом $l_{43} = 7$ и:

$L_{b} =$ 
$\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 5 & 1 & 0\\
4 & 6 & 7 & 1
\end{pmatrix}$

$U_{b} =$
$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 0 & 4
\end{pmatrix}$

Проверим с помощью `numpy`:

In [12]:
L_b = np.array([[1, 0, 0, 0], [2, 1, 0, 0], [3, 5, 1, 0], [4, 6, 7, 1]])
U_b = np.array([[1, 1, 2, 4], [0, 3, 4, 1], [0, 0, 3, 1], [0, 0, 0, 4]])

print(f'Матрица L_b\n{L_b}\n')
print(f'Матрица U_b\n{U_b}\n')
print(f'Матрица B = L_b * U_b\n{np.dot(L_b, U_b)}')

Матрица L_b
[[1 0 0 0]
 [2 1 0 0]
 [3 5 1 0]
 [4 6 7 1]]

Матрица U_b
[[1 1 2 4]
 [0 3 4 1]
 [0 0 3 1]
 [0 0 0 4]]

Матрица B = L_b * U_b
[[ 1  1  2  4]
 [ 2  5  8  9]
 [ 3 18 29 18]
 [ 4 22 53 33]]


### Задача 3

_**Условие:**_

Решите систему линейных уравнений методом $LU$-разложения:

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

_**Решение:**_

Матрица коэффициентов $A$:
$\begin{pmatrix}
2 & 1 & 3\\ 
11 & 7 & 5\\ 
9 & 8 & 4
\end{pmatrix}$

Матрица $L$:
$\begin{pmatrix}
1 & 0 & 0 \\ 
l_{21} & 1 & 0 \\ 
l_{31} & l_{32} & 1
\end{pmatrix}$

- $l_{21}$ определяется путем умножения 1-ой строки на 11/2
- $l_{31}$ определяется путем умножения 1-ой строки на 9/2

Таким образом $l_{21} = 11/2$, $l_{31} = 9/2$, а получившаяся матрица $U$ после преобразований будет иметь вид:

$\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 3/2 & -23/2 \\ 
0 & 7/2 & -19/2
\end{pmatrix}$

$l_{32}$ определяется путем умножения 2-ой строки на 7/3.

Таким образом $l_{32} = 7/3$ и:

$L =$ 
$\begin{pmatrix}
1 & 0 & 0 \\ 
11/2 & 1 & 0 \\ 
9/2 & 7/3 & 1
\end{pmatrix}$

$U =$
$\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 3/2 & -23/2 \\ 
0 & 0 & 52/3
\end{pmatrix}$

Решаем систему $Ly=b$:

$\begin{cases}
y_{1}=1 \\
11/2y_{1}+y_{2}=-6 \\
9/2y_{1}+7/3y_{2}+y_{3}=-5
\end{cases}$

$y_{1}=1$, $y_{2}=-23/2$, $y_{3}=52/3$

Решаем систему $Ux=y$:

$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
3/2x_{2}-23/2x_{3}=-23/2 \\
52/3x_{3}=52/3
\end{cases}$

$x_{3}=1$, $x_{2}=0$, $x_{1}=-1$

Произведём проверку, подставив полученные значения переменных в исходную систему:

$\begin{cases}
2\cdot(-1)+0+3\cdot 1=1 \\
11\cdot(-1)+7\cdot 0+5\cdot 1=-6 \\
9\cdot(-1)+8\cdot 0+4\cdot 1=-5
\end{cases}$

Таким образом, найденное решение верно.

### Задача 4

_**Условие:**_

Решите систему линейных уравнений методом Холецкого:

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

_**Решение:**_

Производим разложение на $LL^{T}$:

$$l_{11}=\sqrt{a_{11}}=\sqrt{81}=9$$
$$l_{21}=\frac{a_{21}}{l_{11}}=\frac{-45}{9}=-5$$
$$l_{31}=\frac{a_{31}}{l_{11}}=\frac{45}{9}=5$$

$$l_{22}=\sqrt{a_{22}-l_{21}^{2}}=\sqrt{50 - ({-5})^{2}}=5$$
$$l_{32}=\frac{1}{l_{22}}\left ( a_{32}-l_{21}l_{31} \right)=\frac{1}{5}\left ( -15 - (-5)\cdot 5 \right )=2$$

$$l_{33}=\sqrt{a_{33}-l_{31}^{2}-l_{32}^{2}}=\sqrt{38-{5}^{2}-{2}^{2}}=3$$

Получаем:

$$L = \begin{pmatrix}
9 & 0 & 0 \\ 
-5 & 5 & 0 \\ 
5 & 2 & 3
\end{pmatrix}, 
\; \; 
L^{T} = \begin{pmatrix}
9 & -5 & 5 \\ 
0 & 5 & 2 \\ 
0 & 0 & 3
\end{pmatrix}.$$

Решаем систему $Ly=b$:

$$\begin{cases}
9y_{1}=531 \\
-5y_{1}+5y_{2}=-460 \\
5y_{1}+2y_{2}+3y_{3}=193
\end{cases}$$

$$y_{1} = 59$$

$$y_{2}=-33$$

$$y_{3}=-12$$

Решаем систему $L^{T}x=y$:

$$\begin{cases}
9x_{1}-5x_{2}+5x_{3}=59 \\
5x_{2}+2x_{3}=-33 \\
3x_{3}=-12
\end{cases}$$

$$x_{3}=-4$$

$$x_{2}=-5$$

$$x_{1}=6$$

Произведём проверку, подставив полученные значения переменных в исходную систему:

$\begin{cases}
81\cdot 6-45\cdot(-5)+45\cdot(-4)=531 \\
-45\cdot 6+50\cdot(-5)-15\cdot(-4)=-460 \\
45\cdot 6-15\cdot(-5)+38\cdot(-4)=193
\end{cases}$

Таким образом, найденное решение верно.