## Практическое задание №2.

## Матрицы и матричные операции.

## Часть 1

### Задача 1

_**Условие:**_

Установите, какие произведения матриц $AB$ и $BA$ определены, и найдите размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

_**Решение:**_

Исходя из правила перемножения матриц и обязательного условия равности количества столбцов 1-ой матрицы количеству строк 2-ой матрицы, получаем следующие выводы:

 а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$ — данные матрицы перемножить нельзя, поскольку число столбцов у $A$ = 2 не равно количеству строк у матрицы $B$ = 4;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$ — для этих матриц определено произведение $AB$ результатом, которого будет матрица $2\times 3$, а произведение $BA$, произвести нельзя, так как в этом случае число столбцов у $B$ = 3 не равно количеству строк у матрицы $A$ = 2;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$ — для данных матриц можно произвести оба произведения $AB$ и $BA$, так как в обоих случаях количество столбцов будет совпадать с количеством строк, в результате при $AB$ получится матрица размерностью $8\times 8$, при $BA$ — $3\times 3$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$ — для квадратных матриц можно произвести оба произведения $AB$ и $BA$, так как в обоих случаях количество столбцов будет совпадать с количеством строк, и также в результате получатся матрицы размерностью $4\times 4$.

### Задача 2

_**Условие:**_

Найдите сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

_**Решение:**_

Поскольку данные матрицы имеют одинаковый порядок, то их сумма будет матрица $C$:

$$С = A + B = 
\begin{pmatrix}
1 & -2\\ 
3 & 0 
\end{pmatrix} + \begin{pmatrix}
4 & -1\\ 
0 & 5 
\end{pmatrix} = \begin{pmatrix}
1 + 4 & -2 + (-1)\\ 
3 + 0 & 0 + 5\\ 
\end{pmatrix}
= \begin{pmatrix}
5 & -3\\ 
3 & 5\\ 
\end{pmatrix}$$

Так как матрицы квадратные, то можно осуществить произведение $AB$ и $BA$:

$$AB = 
\begin{pmatrix}
1 & -2\\ 
3 & 0 
\end{pmatrix} \cdot \begin{pmatrix}
4 & -1\\ 
0 & 5 
\end{pmatrix} = \begin{pmatrix}
(1 * 4 + (-2) * 0) & (1 * (-1) + (-2) * 5)\\ 
(3 * 4 + 0 * 0) & (3 * (-1) + 0 * 5)\\ 
\end{pmatrix}
= \begin{pmatrix}
4 & -11\\ 
12 & -3\\ 
\end{pmatrix}$$

$$BA = 
\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} \cdot \begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} = \begin{pmatrix}
(4 * 1 + (-1) * 3) & (4 * (-2) + (-1) * 0)\\ 
(0 * 1 + 5 * 3) & (0 * (-2) + 5 * 0)\\ 
\end{pmatrix}
= \begin{pmatrix}
1 & -8\\ 
15 & 0\\ 
\end{pmatrix}$$

Проверим с помощью `NumPy`:

In [1]:
import numpy as np

In [2]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

print(f'Матрица A\n{A}\n')
print(f'Матрица B\n{B}\n')
print(f'Матрица С = A + B\n{A + B}')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BA\n{np.dot(B, A)}')

Матрица A
[[ 1 -2]
 [ 3  0]]

Матрица B
[[ 4 -1]
 [ 0  5]]

Матрица С = A + B
[[ 5 -3]
 [ 3  5]]
Матрица AB
[[  4 -11]
 [ 12  -3]]
Матрица BA
[[ 1 -8]
 [15  0]]


### Задача 3

_**Условие:**_

Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислите линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

_**Решение:**_

Так как матрицы одного размера, используя сочетательное свойство сложения и свойства умножения на число, преобразуем комбинацию следующим образом:

$3A-2B+4C = 3 \cdot \begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix} + ((-2) \cdot \begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix} + 4 \cdot \begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}) = \begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix} + (\begin{pmatrix}
0 & -10\\ 
-4 & 2
\end{pmatrix} + \begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix}) = \begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix} + \begin{pmatrix}
8 & -26\\ 
0 & 6
\end{pmatrix} = \begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$

In [3]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

print(f'Линейная комбинация 3A - 2B + 4C:\n{3 * A - 2 * B + 4 * C}')

Линейная комбинация 3A - 2B + 4C:
[[ 11  -5]
 [  9 -12]]


### Задача 4

_**Условие:**_

Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислите $AA^{T}$ и $A^{T}A$.

_**Решение:**_

Поскольку при транспонировании строки исходной матрицы становятся столбцами, а столбцы — строками, то получаем:

$A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}, \;A^{T}=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3 
\end{pmatrix}$

Тогда $AA^{T}$ и $A^{T}A$:

$$A \cdot A^{T} = \begin{pmatrix}
(4 * 4) + (1 * 1) & (4 * 5) + (1 * (-2)) & (4 * 2) + (1 * 3)\\ 
(5 * 4) + ((-2) * 1) & (5 * 5) + ((-2) * (-2)) & (5 * 2) + ((-2) * 3)\\ 
(2 * 4) + (3 * 1) & (2 * 5) + (3 * (-2)) & (2 * 2) + (3 * 3)
\end{pmatrix} = \begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\ 
11 & 4 & 13
\end{pmatrix}$$<br>
$$A^{T} \cdot A = \begin{pmatrix}
(4 * 4) + (5 * 5) + (2 * 2) & (4 * 1) + (5 * (-2)) + (2 * 3)\\ 
(1 * 4) + ((-2) * 5) + (3 * 2) & (1 * 1) + ((-2) * (-2)) + (3 * 3)
\end{pmatrix} = \begin{pmatrix}
45 & 0\\ 
0 & 14
\end{pmatrix}$$

In [4]:
A = np.array([[4, 1], [5, -2], [2, 3]])

print(f'Произведение А на транспонированную А:\n{np.dot(A, A.T)}')
print(f'Произведение транспонированной А на А:\n{np.dot(A.T, A)}')

Произведение А на транспонированную А:
[[17 18 11]
 [18 29  4]
 [11  4 13]]
Произведение транспонированной А на А:
[[45  0]
 [ 0 14]]


## Часть 2

### Задача 1

_**Условие:**_

Вычислите определитель:

   a)

$$\begin{pmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{pmatrix}$$

   б)
    
$$\begin{pmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{pmatrix}$$
    
   в)

$$\begin{pmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{pmatrix}$$

_**Решение:**_

_**a)**_

Так как данная матрица 2-ого порядка, то определитель равен разности произведения элементов, стоящих на главной диагонали этой матрицы, и элементов, располагающихся на её побочной диагонали:

$det\begin{pmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{pmatrix} = sinx \cdot sinx - (-cosx) \cdot cosx = sin^2x + cos^2x = 1$ 

Также, поскольку в методичке разобран пример с такой же матрицей и определено, что эта матрица является ортоганальной, то обращаясь к свойствам определителя, можно сразу сказать, что определитель такой матрицы равен $detA = \pm1.$

_**б)**_

Данная матрица является верхне-треугольной, поэтому, исходя из свойств определителя, для такой матрицы определитель равен произведению элементов, стоящих на её главной диагонали:

$det\begin{pmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{pmatrix} = 4 * 5 * 9 = 180$

In [5]:
Up_Triang_Matrix = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(f'Матрица:\n{Up_Triang_Matrix}')
print(f'Определитель:\n{np.linalg.det(Up_Triang_Matrix)}')

Матрица:
[[4 2 3]
 [0 5 1]
 [0 0 9]]
Определитель:
180.0


_**в)**_

Поскольку данная матрица порядка $n\geq2$, то вычислим определитель разложением, к примеру, по 1-ой строке:

$det\begin{pmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{pmatrix} = (-1)^{1 + 1} \cdot 1 \cdot \begin{pmatrix}
5 & 6\\ 
8 & 9
\end{pmatrix} + (-1)^{1 + 2} \cdot 2 \cdot \begin{pmatrix}
4 & 6\\ 
7 & 9
\end{pmatrix} + (-1)^{1 + 3} \cdot 3 \cdot \begin{pmatrix}
4 & 5\\ 
7 & 8
\end{pmatrix} = 1 \cdot (5 * 9 - 6 * 8) - 2 \cdot (4 * 9 - 6 * 7) + 3 \cdot (4 * 8 - 5 * 7) = - 3 + 12 - 9 = 0$

In [6]:
Funny_Matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Матрица:\n{Funny_Matrix}')
print(f'Определитель:\n{np.linalg.det(Funny_Matrix):.0f}')

Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Определитель:
-0


### Задача 2

_**Условие:**_

Определитель матрицы $A$ равен $4$. Найдите:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

_**Решение:**_

$a)$ В условии не сказано, что матрица $A$ квадратная, но так как $A^2$ означает умножение данной матрицы на саму себя, и предположив, что она квадратная, то исходя из свойств определителя, для двух квадратных матриц одинакового размера: $det(AB)=detA\cdot detB$ получаем, что $det(A^2 = A \cdot A) = detA \cdot detA = 16$

$б)$ Исходя из свойств определителя, определитель транспонированной матрицы равен определителю исходной $det(A^{T}) = det(A) = 4$

$в)$ Исходя из свойств определителя, умножение строки или столбца матрицы на число $\lambda$ приведёт к умножению определителя матрицы на то же число: $det(2A) = 2 \cdot 4 = 8$

### Задача 3

_**Условие:**_

Докажите, что матрица:

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

_**Решение:**_

По определению: матрица называется вырожденной, если её определитель равен нулю. Вычислим определитель:

In [7]:
Any_Matrix = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'Матрица:\n{Any_Matrix}')
print(f'Определитель:\n{np.linalg.det(Any_Matrix)}')

Матрица:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]
Определитель:
0.0


Таким образом заданная матрица является вырожденной.

### Задача 4

_**Условие:**_

Найдите ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

_**Решение:**_

_**a)**_

Размерность матрицы: $3 \times 3$, таким образом ранг будет $R \leq 3$. 3-я строка является линейной комбинацией 1-ой и 2-ой (сумма элементов), поэтому будем искать минор 2-ого порядка. Если взять минор из 1-ого и 2-ого элементов 1-ой строки и 1-ого и 2-ого элементов 2-ой строки, то его определитель будет равен -1, таким образом ранг матрицы равен 2.  

In [8]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
print(f'Матрица:\n{a}')
print(f'Ранг:\n{np.linalg.matrix_rank(a)}')

Матрица:
[[1 2 3]
 [1 1 1]
 [2 3 4]]
Ранг:
2


_**б)**_

Размерность матрицы: $4 \times 4$, таким образом ранг будет $R \leq 4$. 3-я строка является линейной комбинацией 1-ой и 2-ой (сумма элементов), поэтому а значит, её можно отбросить:

$$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
2 & 3 & 5 & 6
\end{pmatrix}$$

Подсчитаем определитель минора 3-х строк со 2-ого по 4-ый столбец:

In [9]:
minor = np.array([[0, 2, 1], [0, 2, 2], [3, 5, 6]])
print(f'Минор:\n{minor}')
print(f'Определитель:\n{np.linalg.det(minor)}')

Минор:
[[0 2 1]
 [0 2 2]
 [3 5 6]]
Определитель:
6.0


Определитель этого минора 3-его порядка не равен 0, поэтому данный минор невырожденный и соответственно ранг матрицы равен 3.

In [10]:
b = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 4, 5]])
print(f'Матрица:\n{b}')
print(f'Ранг:\n{np.linalg.matrix_rank(b)}')

Матрица:
[[0 0 2 1]
 [0 0 2 2]
 [0 0 4 3]
 [2 3 4 5]]
Ранг:
3
